import 'dart:math';

/// Type of noise generated by the AGI noise channel.
enum NoiseType {
  /// Periodic noise (linear feedback shift register with narrow pulse train).
  periodic,

  /// White noise (pseudo-random shift register feedback).
  white,
}

/// Represents an audible tone note or rest segment in an AGI sound voice.
class AgiNote {
  /// Start time in 1/60th second ticks from the beginning of the sound.
  final int startTime;

  /// Duration in 1/60th second ticks.
  final int duration;

  /// Raw 10-bit frequency divider value from the SN76496 tone generator.
  final int frequencyCount;

  /// Attenuation (volume level) from 0 (loudest) to 15 (silence).
  final int attenuation;

  const AgiNote({
    required this.startTime,
    required this.duration,
    required this.frequencyCount,
    required this.attenuation,
  });

  /// Whether this note is silent (attenuation == 15 or 0 frequency).
  bool get isSilent => attenuation == 15 || frequencyCount == 0;

  /// End time in 1/60th second ticks.
  int get endTime => startTime + duration;

  /// SN76496 master clock in IBM PCjr / Tandy 1000:
  /// 3.579545 MHz / 32 = 111860.78125 Hz.
  static const double tandyClockDiv32 = 111860.78125;

  /// Calculated frequency in Hertz.
  double get frequencyInHz =>
      frequencyCount > 0 ? (tandyClockDiv32 / frequencyCount) : 0.0;

  /// Converts this note's frequency to the closest MIDI note number (0..127).
  ///
  /// Standard 12-TET tuning ($A4 = 440$ Hz, MIDI 69):
  /// Note number $m = 69 + 12 \cdot \log_2(f / 440.0)$.
  ///
  /// If [useAgiLegacyFormula] is true, uses the historical formula
  /// $36 + 12 \cdot \log_2(f / 64.0)$ matching early AGI extractors.
  int toMidiNoteNumber({bool useAgiLegacyFormula = false}) {
    if (frequencyCount <= 0 || isSilent) return 0;
    final hz = frequencyInHz;
    if (hz <= 0) return 0;

    if (useAgiLegacyFormula) {
      final midi = (36.0 + 12.0 * (log(hz / 64.0) / ln2)).round();
      return midi.clamp(0, 127);
    }

    final midi = (69.0 + 12.0 * (log(hz / 440.0) / ln2)).round();
    return midi.clamp(0, 127);
  }

  /// Converts attenuation (0..15) to a MIDI velocity (0..127).
  int toMidiVelocity() {
    if (isSilent) return 0;
    return (100 - (6 * attenuation)).clamp(1, 127);
  }

  @override
  String toString() =>
      'AgiNote(start: $startTime, dur: $duration, freq: $frequencyCount (${frequencyInHz.toStringAsFixed(1)}Hz), att: $attenuation)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgiNote &&
          runtimeType == other.runtimeType &&
          startTime == other.startTime &&
          duration == other.duration &&
          frequencyCount == other.frequencyCount &&
          attenuation == other.attenuation;

  @override
  int get hashCode => Object.hash(startTime, duration, frequencyCount, attenuation);
}

/// Represents a sequence of notes played sequentially on one tone voice channel.
class ToneChannel {
  final List<AgiNote> notes;

  const ToneChannel({required this.notes});

  /// Total length in 1/60th second ticks.
  int get length => notes.isEmpty ? 0 : notes.last.endTime;

  @override
  String toString() => 'ToneChannel(notes: ${notes.length}, length: ${length}t)';
}

/// Represents a noise sound event played on the noise channel.
class AgiNoise {
  /// Start time in 1/60th second ticks.
  final int startTime;

  /// Duration in 1/60th second ticks.
  final int duration;

  /// Frequency divider mode (0x10 = high, 0x20 = med, 0x40 = low, 0x00 = tone 3).
  final int frequencyCount;

  /// Attenuation (0 = loudest, 15 = silence).
  final int attenuation;

  /// Noise feedback mode (periodic pulse vs white noise).
  final NoiseType type;

  const AgiNoise({
    required this.startTime,
    required this.duration,
    required this.frequencyCount,
    required this.attenuation,
    required this.type,
  });

  bool get isSilent => attenuation == 15;
  int get endTime => startTime + duration;

  @override
  String toString() =>
      'AgiNoise(start: $startTime, dur: $duration, freqMode: 0x${frequencyCount.toRadixString(16)}, type: ${type.name}, att: $attenuation)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgiNoise &&
          runtimeType == other.runtimeType &&
          startTime == other.startTime &&
          duration == other.duration &&
          frequencyCount == other.frequencyCount &&
          attenuation == other.attenuation &&
          type == other.type;

  @override
  int get hashCode => Object.hash(startTime, duration, frequencyCount, attenuation, type);
}

/// Represents the noise channel sequence of an AGI sound resource.
class NoiseChannel {
  final List<AgiNoise> noises;

  const NoiseChannel({required this.noises});

  /// Total length in 1/60th second ticks.
  int get length => noises.isEmpty ? 0 : noises.last.endTime;

  @override
  String toString() => 'NoiseChannel(noises: ${noises.length}, length: ${length}t)';
}

/// Represents a parsed 4-channel AGI Sound Resource (3 tone channels + 1 noise channel).
class AgiSound {
  /// Up to 3 tone voice channels.
  final List<ToneChannel> voices;

  /// Optional noise channel.
  final NoiseChannel? noise;

  AgiSound({
    required this.voices,
    this.noise,
  }) {
    for (final voice in voices) {
      if (voice.notes.isEmpty) {
        throw ArgumentError("ToneChannel in voices cannot have an empty notes list.");
      }
    }
    if (noise != null && noise!.noises.isEmpty) {
      throw ArgumentError("NoiseChannel cannot have an empty noises list.");
    }
  }

  /// Total duration of the sound in 1/60th second ticks.
  int get length {
    int maxLen = noise?.length ?? 0;
    for (final v in voices) {
      if (v.length > maxLen) {
        maxLen = v.length;
      }
    }
    return maxLen;
  }

  /// Duration in seconds.
  double get durationInSeconds => length / 60.0;

  /// Whether this sound resource contains no audible voices or noise.
  bool get isEmpty => voices.isEmpty && (noise == null || noise!.noises.isEmpty);

  @override
  String toString() =>
      'AgiSound(voices: ${voices.length}, hasNoise: ${noise != null}, length: ${length}t (${durationInSeconds.toStringAsFixed(2)}s))';
}
