import 'dart:convert';
import 'dart:io';
import 'package:flutter_agigame/domain/game_state_snapshot.dart';
import 'package:flutter_agigame/engine/agi_game_engine.dart';
import 'package:flutter_agigame/loader/resource_loader.dart';
import 'package:test/test.dart';

void main() {
  const userSnapshotJson = '''
{
  "version": "1.0",
  "timestamp": "2026-08-16T17:34:31.270621",
  "label": "Room 6 (Cycle 5063)",
  "roomNumber": 6,
  "cycleCount": 5063,
  "speedHz": 20.0,
  "score": 2,
  "maxScore": 210,
  "soundOn": true,
  "isPaused": false,
  "isInputEnabled": true,
  "isUserControl": false,
  "lastSubmittedCommand": "look",
  "lastError": "I don't understand 'papers'",
  "variables": {
    "0": 6,
    "1": 8,
    "3": 2,
    "7": 210,
    "8": 10,
    "10": 2,
    "11": 18,
    "12": 4,
    "16": 13,
    "22": 1,
    "24": 41,
    "31": 147,
    "32": 105,
    "36": 3,
    "37": 67,
    "38": 133,
    "40": 75,
    "41": 142,
    "42": 75,
    "43": 142,
    "44": 20,
    "47": 11,
    "48": 1,
    "56": 1,
    "57": 77,
    "58": 147,
    "59": 1,
    "60": 1,
    "61": 1,
    "67": 2,
    "69": 1,
    "80": 23,
    "81": 163,
    "83": 46,
    "100": 70,
    "101": 123,
    "115": 15,
    "116": 4,
    "120": 15,
    "125": 8,
    "127": 1,
    "128": 102,
    "134": 1,
    "136": 4,
    "141": 1,
    "142": 2,
    "143": 3,
    "144": 4,
    "145": 5,
    "246": 3,
    "247": 5,
    "249": 10
  },
  "activeFlags": [
    9,
    14,
    34,
    37,
    38,
    46,
    47,
    48,
    104,
    106,
    107,
    126,
    129
  ],
  "activeControllers": [],
  "itemRooms": {
    "0": 0,
    "1": 34,
    "2": 0,
    "3": 39,
    "4": 11,
    "5": 10,
    "6": 42,
    "7": 28,
    "8": 121,
    "9": 114,
    "10": 0,
    "11": 10,
    "12": 2,
    "13": 39,
    "14": 36,
    "15": 29,
    "16": 123,
    "17": 10,
    "18": 22,
    "19": 39,
    "20": 124,
    "21": 10,
    "22": 39,
    "23": 125,
    "24": 41,
    "25": 125,
    "26": 0,
    "27": 0,
    "28": 10,
    "29": 39,
    "30": 126,
    "31": 10,
    "32": 39,
    "33": 6,
    "34": 21,
    "35": 39,
    "36": 127,
    "37": 5,
    "38": 2,
    "39": 39,
    "40": 6,
    "41": 6,
    "42": 255,
    "43": 2,
    "44": 2,
    "45": 6,
    "46": 5,
    "47": 0,
    "48": 38,
    "49": 6,
    "50": 6,
    "51": 6,
    "52": 84,
    "53": 49,
    "54": 2
  },
  "strings": {
    "0": "]"
  },
  "objects": [
    {
      "number": 0,
      "x": 75,
      "y": 142,
      "prevX": 74,
      "prevY": 142,
      "view": 13,
      "loop": 0,
      "cel": 8,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 2,
      "cycleTimer": 2,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": true,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 1,
      "x": 63,
      "y": 119,
      "prevX": 63,
      "prevY": 119,
      "view": 208,
      "loop": 0,
      "cel": 0,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": true,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 2,
      "x": 62,
      "y": 92,
      "prevX": 62,
      "prevY": 92,
      "view": 208,
      "loop": 0,
      "cel": 1,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 3,
      "x": 65,
      "y": 93,
      "prevX": 65,
      "prevY": 93,
      "view": 208,
      "loop": 0,
      "cel": 2,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 4,
      "x": 32,
      "y": 74,
      "prevX": 32,
      "prevY": 74,
      "view": 208,
      "loop": 0,
      "cel": 6,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 5,
      "x": 127,
      "y": 112,
      "prevX": 127,
      "prevY": 112,
      "view": 208,
      "loop": 0,
      "cel": 4,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 6,
      "x": 131,
      "y": 122,
      "prevX": 131,
      "prevY": 122,
      "view": 208,
      "loop": 0,
      "cel": 5,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 7,
      "x": 125,
      "y": 105,
      "prevX": 125,
      "prevY": 105,
      "view": 208,
      "loop": 0,
      "cel": 3,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 14,
      "x": 109,
      "y": 147,
      "prevX": 109,
      "prevY": 147,
      "view": 199,
      "loop": 0,
      "cel": 8,
      "priority": 15,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 3,
      "cycleTimer": 3,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 15,
      "x": 105,
      "y": 147,
      "prevX": 105,
      "prevY": 147,
      "view": 193,
      "loop": 1,
      "cel": 4,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 2,
      "stepTimer": 2,
      "cycleTime": 2,
      "cycleTimer": 2,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    }
  ],
  "callStack": [],
  "scanStartIp": 0
}
''';

  test('Restore and investigate user snapshot', () {
    final kq3Dir = Directory('reference_games/kings-quest-3');
    if (!kq3Dir.existsSync()) return;

    final loader = AgiResourceLoader.fromDirectorySync('reference_games/kings-quest-3');
    final engine = AgiGameEngine(resourceLoader: loader);
    engine.initializeGame();

    final snapshot = AgiGameStateSnapshot.fromJson(
      jsonDecode(userSnapshotJson) as Map<String, dynamic>,
    );

    engine.restoreSnapshot(snapshot);

    print('Restored state: room=${engine.memory.getVar(0)}, prevRoom=${engine.memory.getVar(1)}');
    print('v123=${engine.memory.getVar(123)}, v125=${engine.memory.getVar(125)}, v127=${engine.memory.getVar(127)}, v133=${engine.memory.getVar(133)}, v134=${engine.memory.getVar(134)}, v137=${engine.memory.getVar(137)}');
    print('v84=${engine.memory.getVar(84)}, v83=${engine.memory.getVar(83)}, v95=${engine.memory.getVar(95)}');

    // Check items in room 255 (carried items)
    final carried = engine.getCarriedItems();
    print('Carried items (${carried.length}):');
    for (final item in carried) {
      print('  #${item.index}: ${item.object.name}');
    }

    // Check all item rooms
    for (int i = 0; i < engine.objects.length; i++) {
      final r = engine.memory.itemRooms[i];
      if (r != null && r != engine.objects[i].startingRoom) {
        print('  Obj #$i "${engine.objects[i].name}" moved from starting room ${engine.objects[i].startingRoom} -> room $r');
      }
    }

    // Check which logic numbers are called in room 6
    final logic6 = loader.loadLogic(6);
    print('Logic 6 calls:');
    // Let's inspect logic 6
  });
}
