import 'dart:convert';
import 'dart:io';
import 'package:flutter_agigame/domain/game_state_snapshot.dart';
import 'package:flutter_agigame/engine/agi_game_engine.dart';
import 'package:flutter_agigame/loader/resource_loader.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('Space Quest 2 Room 22', () {
    test('restores user state and loads room 22 picture and logic', () async {
      final sq2Dir = Directory('reference_games/space-quest-2');
      if (!sq2Dir.existsSync()) return;

      final loader = AgiResourceLoader.fromDirectorySync(sq2Dir.path);
      final engine = AgiGameEngine(resourceLoader: loader);

      const jsonStr = '''
{
  "version": "1.0",
  "timestamp": "2026-08-18T00:00:18.423574",
  "label": "Room 22 (Cycle 6306)",
  "roomNumber": 22,
  "cycleCount": 6306,
  "speedHz": 20.0,
  "score": 63,
  "maxScore": 250,
  "soundOn": false,
  "isPaused": true,
  "isInputEnabled": true,
  "isUserControl": true,
  "lastSubmittedCommand": "swing",
  "variables": {
    "0": 22,
    "1": 16,
    "3": 63,
    "7": 250,
    "8": 10,
    "10": 2,
    "11": 17,
    "12": 14,
    "15": 3,
    "16": 70,
    "22": 1,
    "24": 41,
    "25": 255,
    "30": 1,
    "31": 1,
    "34": 66,
    "35": 89,
    "41": 41,
    "50": 2,
    "51": 66,
    "52": 66,
    "54": 89,
    "55": 66,
    "64": 2,
    "68": 249,
    "70": 78,
    "71": 68,
    "73": 17,
    "75": 78,
    "76": 68,
    "77": 78,
    "78": 68,
    "83": 2,
    "85": 61,
    "86": 1,
    "87": 2,
    "88": 3,
    "90": 4,
    "91": 5,
    "93": 48,
    "94": 1,
    "99": 3,
    "102": 1,
    "107": 3,
    "108": 14,
    "112": 6
  },
  "activeFlags": [
    8,
    14,
    33,
    34,
    57,
    58,
    61,
    73,
    77,
    78,
    81,
    84,
    89,
    92,
    93,
    122,
    199,
    200,
    201,
    202,
    203,
    204,
    205
  ],
  "activeControllers": [],
  "itemRooms": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 255,
    "22": 0,
    "23": 0,
    "24": 255,
    "25": 0,
    "26": 255,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 255,
    "35": 255,
    "36": 255,
    "37": 255,
    "38": 0,
    "39": 0
  },
  "strings": {
    "0": ">",
    "1": "Roger Wilco",
    "4": "Ver. 2.0F"
  },
  "objects": [
    {
      "number": 0,
      "x": 78,
      "y": 68,
      "prevX": 78,
      "prevY": 67,
      "view": 70,
      "loop": 0,
      "cel": 8,
      "priority": 11,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 1,
      "x": 102,
      "y": 97,
      "prevX": 102,
      "prevY": 97,
      "view": 62,
      "loop": 2,
      "cel": 0,
      "priority": 8,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 2,
      "x": 104,
      "y": 68,
      "prevX": 104,
      "prevY": 68,
      "view": 62,
      "loop": 1,
      "cel": 0,
      "priority": 10,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 2,
      "cycleTimer": 2,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 3,
      "x": 69,
      "y": 66,
      "prevX": 69,
      "prevY": 66,
      "view": 71,
      "loop": 0,
      "cel": 0,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 4,
      "x": 0,
      "y": 11,
      "prevX": 0,
      "prevY": 11,
      "view": 0,
      "loop": 0,
      "cel": 0,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": true,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 10,
      "x": 84,
      "y": 66,
      "prevX": 85,
      "prevY": 66,
      "view": 71,
      "loop": 0,
      "cel": 1,
      "priority": 10,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 7,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 66,
      "targetY": 66,
      "stepDistance": 0,
      "targetFlag": 35,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    }
  ],
  "callStack": [],
  "scanStartIp": 0,
  "scanStarts": {},
  "isRoomTransition": false
}
''';

      final snapshot = AgiGameStateSnapshot.fromJson(jsonDecode(jsonStr) as Map<String, dynamic>);
      engine.initializeGame();
      engine.restoreSnapshot(snapshot);

      expect(engine.memory.getVar(0), 22);
      expect(engine.currentPic, isNotNull);
    });
  });
}
