import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_agigame/domain/game_state_snapshot.dart';
import 'package:flutter_agigame/engine/agi_game_engine.dart';
import 'package:flutter_agigame/loader/resource_loader.dart';

void main() {
  const room9Json = '''{
  "version": "1.0",
  "timestamp": "2026-08-20T00:45:59.860607",
  "label": "Room 9 (Cycle 3022)",
  "roomNumber": 9,
  "pictureNumber": 9,
  "cycleCount": 3022,
  "speedHz": 20.0,
  "score": 7,
  "maxScore": 250,
  "soundOn": true,
  "isPaused": false,
  "isInputEnabled": false,
  "isUserControl": true,
  "isStatusLineEnabled": true,
  "statusRow": 0,
  "lastSubmittedCommand": "get suit",
  "lastError": "I don't understand 'pres'",
  "variables": {
    "0": 9,
    "1": 8,
    "3": 7,
    "7": 250,
    "8": 10,
    "10": 2,
    "11": 26,
    "12": 1,
    "15": 3,
    "16": 6,
    "22": 1,
    "24": 41,
    "36": 4,
    "38": 14,
    "39": 202,
    "50": 2,
    "51": 100,
    "52": 72,
    "53": 2,
    "54": 159,
    "55": 140,
    "64": 2,
    "68": 249,
    "70": 27,
    "71": 112,
    "73": 26,
    "75": 106,
    "76": 114,
    "77": 106,
    "78": 114,
    "86": 1,
    "87": 2,
    "88": 3,
    "90": 4,
    "91": 5,
    "108": 1,
    "112": 6
  },
  "activeFlags": [
    8,
    9,
    11,
    14,
    40,
    73,
    87
  ],
  "activeControllers": [],
  "itemRooms": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 255,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 255,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0
  },
  "strings": {
    "0": ">",
    "4": "Ver. 2.0F"
  },
  "objects": [
    {
      "number": 0,
      "x": 106,
      "y": 114,
      "prevX": 106,
      "prevY": 113,
      "view": 6,
      "loop": 2,
      "cel": 1,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 1,
      "x": 60,
      "y": 117,
      "prevX": 60,
      "prevY": 117,
      "view": 41,
      "loop": 2,
      "cel": 2,
      "priority": 5,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": false,
      "isCycling": true,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 2,
      "x": 92,
      "y": 142,
      "prevX": 90,
      "prevY": 142,
      "view": 44,
      "loop": 0,
      "cel": 2,
      "priority": 4,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 3,
      "stepSize": 2,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 137,
      "targetY": 142,
      "stepDistance": 0,
      "targetFlag": 30,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 3,
      "x": 14,
      "y": 142,
      "prevX": 12,
      "prevY": 142,
      "view": 44,
      "loop": 0,
      "cel": 2,
      "priority": 4,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 3,
      "stepSize": 2,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 137,
      "targetY": 142,
      "stepDistance": 0,
      "targetFlag": 31,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 4,
      "x": 40,
      "y": 142,
      "prevX": 38,
      "prevY": 142,
      "view": 44,
      "loop": 0,
      "cel": 0,
      "priority": 4,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 3,
      "stepSize": 2,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 137,
      "targetY": 142,
      "stepDistance": 0,
      "targetFlag": 32,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 5,
      "x": 52,
      "y": 142,
      "prevX": 50,
      "prevY": 142,
      "view": 44,
      "loop": 0,
      "cel": 1,
      "priority": 4,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 3,
      "stepSize": 2,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 137,
      "targetY": 142,
      "stepDistance": 0,
      "targetFlag": 33,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 6,
      "x": 45,
      "y": 142,
      "prevX": 40,
      "prevY": 142,
      "view": 44,
      "loop": 1,
      "cel": 0,
      "priority": 5,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 3,
      "stepSize": 5,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 130,
      "targetY": 142,
      "stepDistance": 0,
      "targetFlag": 34,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 7,
      "x": 130,
      "y": 142,
      "prevX": 125,
      "prevY": 142,
      "view": 44,
      "loop": 1,
      "cel": 4,
      "priority": 5,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 0,
      "stepSize": 5,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 130,
      "targetY": 142,
      "stepDistance": 0,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 8,
      "x": 115,
      "y": 142,
      "prevX": 110,
      "prevY": 142,
      "view": 44,
      "loop": 1,
      "cel": 3,
      "priority": 5,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 3,
      "stepSize": 5,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 3,
      "targetX": 130,
      "targetY": 142,
      "stepDistance": 0,
      "targetFlag": 36,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 9,
      "x": 132,
      "y": 142,
      "prevX": 131,
      "prevY": 142,
      "view": 44,
      "loop": 2,
      "cel": 1,
      "priority": 7,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 0,
      "stepSize": 10,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 132,
      "targetY": 142,
      "stepDistance": 0,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 10,
      "x": 73,
      "y": 108,
      "prevX": 73,
      "prevY": 108,
      "view": 41,
      "loop": 3,
      "cel": 0,
      "priority": 6,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": true,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 11,
      "x": 72,
      "y": 107,
      "prevX": 72,
      "prevY": 107,
      "view": 46,
      "loop": 1,
      "cel": 0,
      "priority": 0,
      "fixedPriority": false,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": true,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": false,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    }
  ],
  "callStack": [],
  "scanStartIp": 0,
  "scanStarts": {},
  "isRoomTransition": false,
  "horizon": 10,
  "loadedLogics": [
    0,
    9
  ]
}''';

  test('Space Quest 2 Room 9: Shakes screen on Room 9 (CRASH) before transitioning to Room 10', () async {
    final sq2Dir = Directory('reference_games/space-quest-2');
    if (!sq2Dir.existsSync()) return;

    final loader = AgiResourceLoader.fromDirectorySync(sq2Dir.path);
    final engine = AgiGameEngine(resourceLoader: loader);
    await engine.initializeGame();

    final snap = AgiGameStateSnapshot.fromJsonString(room9Json);
    engine.restoreSnapshot(snap);

    int shakesInRoom9 = 0;
    int shakesInRoom10 = 0;

    engine.addListener(() {
      if (engine.shakeOffsetX != 0.0 || engine.shakeOffsetY != 0.0) {
        if (engine.currentRoom == 9) {
          shakesInRoom9++;
        } else if (engine.currentRoom == 10) {
          shakesInRoom10++;
        }
      }
    });

    for (int i = 0; i < 400; i++) {
      if (engine.activeDialog != null) {
        engine.dismissDialog();
      }
      await engine.tick();
      if (engine.currentRoom == 10) {
        for (int j = 0; j < 20; j++) {
          await engine.tick();
        }
        break;
      }
    }

    expect(shakesInRoom9, greaterThan(0), reason: 'Screen should shake in Room 9');
    expect(shakesInRoom10, equals(0), reason: 'Screen should NOT shake in Room 10');
  });
}
