import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_agigame/domain/game_state_snapshot.dart';
import 'package:flutter_agigame/engine/agi_game_engine.dart';
import 'package:flutter_agigame/loader/resource_loader.dart';
import 'package:flutter_agigame/logic/disassembler/disassembly_formatter.dart';

void main() {
  test('Analyze SQ2 Room 87 and Status Line behavior', () async {
    final sq2Dir = Directory('reference_games/space-quest-2');
    if (!sq2Dir.existsSync()) return;

    final loader = AgiResourceLoader.fromDirectorySync(sq2Dir.path);
    final formatter = const DisassemblyFormatter();
    final logic86 = loader.loadLogic(86);
    File('scratch/sq2_logic86.txt').writeAsStringSync(formatter.formatScript(logic86));

    final logic87 = loader.loadLogic(87);
    File('scratch/sq2_logic87.txt').writeAsStringSync(formatter.formatScript(logic87));

    // Now let's test restoring the user's snapshot into engine!
    const jsonStr = '''{
  "version": "1.0",
  "timestamp": "2026-08-19T23:53:38.799435",
  "label": "Room 87 (Cycle 1009)",
  "roomNumber": 87,
  "pictureNumber": 87,
  "cycleCount": 1009,
  "speedHz": 30.0,
  "score": 186,
  "maxScore": 250,
  "soundOn": true,
  "isPaused": true,
  "isInputEnabled": true,
  "isUserControl": true,
  "lastSubmittedCommand": "cut glass",
  "variables": {
    "0": 87,
    "1": 86,
    "3": 186,
    "7": 250,
    "8": 10,
    "10": 1,
    "11": 31,
    "12": 28,
    "15": 3,
    "22": 1,
    "24": 41,
    "50": 2,
    "51": 80,
    "52": 97,
    "54": 92,
    "55": 106,
    "64": 2,
    "68": 249,
    "70": 153,
    "71": 100,
    "73": 31,
    "75": 80,
    "76": 99,
    "77": 80,
    "78": 99,
    "83": 2,
    "85": 61,
    "86": 1,
    "87": 2,
    "88": 3,
    "90": 4,
    "91": 5,
    "93": 48,
    "94": 6,
    "99": 3,
    "100": 42,
    "101": 146,
    "102": 1,
    "103": 2,
    "104": 97,
    "105": 28,
    "107": 3,
    "108": 28,
    "110": 84,
    "111": 4,
    "112": 6,
    "122": 1,
    "125": 3,
    "127": 3,
    "129": 232,
    "131": 119,
    "135": 6,
    "137": 4,
    "138": 118,
    "139": 101,
    "140": 66,
    "141": 4
  },
  "activeFlags": [
    8,
    9,
    14,
    30,
    32,
    35,
    57,
    58,
    73,
    77,
    78,
    80,
    81,
    84,
    89,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    109,
    111,
    118,
    119,
    122,
    125,
    126,
    127,
    198,
    199,
    200,
    201,
    202,
    203,
    204,
    205,
    206,
    207,
    208,
    210,
    211,
    213,
    214,
    215
  ],
  "activeControllers": [],
  "itemRooms": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 255,
    "22": 0,
    "23": 0,
    "24": 255,
    "25": 0,
    "26": 255,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 255,
    "33": 255,
    "34": 255,
    "35": 255,
    "36": 255,
    "37": 0,
    "38": 0,
    "39": 0
  },
  "strings": {
    "0": ">",
    "1": "Roger Wilco",
    "4": "Ver. 2.0F"
  },
  "objects": [
    {
      "number": 0,
      "x": 80,
      "y": 99,
      "prevX": 80,
      "prevY": 99,
      "view": 0,
      "loop": 2,
      "cel": 0,
      "priority": 8,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": true,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 80,
      "targetY": 97,
      "stepDistance": 0,
      "ignoreHorizon": false,
      "ignoreBlocks": true,
      "ignoreObjects": false,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 1,
      "x": 79,
      "y": 100,
      "prevX": 79,
      "prevY": 100,
      "view": 182,
      "loop": 0,
      "cel": 9,
      "priority": 9,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 2,
      "cycleTimer": 2,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": false,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": true,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 2,
      "x": 83,
      "y": 67,
      "prevX": 83,
      "prevY": 67,
      "view": 192,
      "loop": 0,
      "cel": 0,
      "priority": 9,
      "fixedPriority": true,
      "fixedLoop": false,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": false,
      "isCycling": true,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": true,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    },
    {
      "number": 10,
      "x": 81,
      "y": 97,
      "prevX": 81,
      "prevY": 97,
      "view": 166,
      "loop": 3,
      "cel": 2,
      "priority": 8,
      "fixedPriority": true,
      "fixedLoop": true,
      "direction": 0,
      "stepSize": 1,
      "stepTime": 1,
      "stepTimer": 1,
      "cycleTime": 1,
      "cycleTimer": 1,
      "isAnimated": true,
      "isDrawn": false,
      "isUpdating": true,
      "isCycling": true,
      "cycleMode": 0,
      "motionType": 0,
      "targetX": 0,
      "targetY": 0,
      "stepDistance": 1,
      "ignoreHorizon": false,
      "ignoreBlocks": true,
      "ignoreObjects": true,
      "onWater": false,
      "onLand": false
    }
  ],
  "callStack": [],
  "scanStartIp": 0,
  "scanStarts": {},
  "isRoomTransition": false,
  "horizon": 10,
  "loadedLogics": [
    0,
    87,
    124
  ],
  "addToPic": [
    {
      "view": 182,
      "loop": 1,
      "cel": 1,
      "x": 79,
      "y": 100,
      "priority": 9,
      "boxPriority": 4
    },
    {
      "view": 182,
      "loop": 1,
      "cel": 0,
      "x": 76,
      "y": 116,
      "priority": 4,
      "boxPriority": 4
    }
  ]
}''';

    final engine = AgiGameEngine(resourceLoader: loader);
    await engine.initializeGame();

    final snap = AgiGameStateSnapshot.fromJsonString(jsonStr);
    snap.restore(engine);

    String getRow(int r) => List.generate(40, (c) => engine.textScreenBuffer.getCell(r, c).char).join();

    expect(engine.isStatusLineEnabled, isTrue);
    expect(getRow(0), contains('Score: 186 of 250'));
    expect(getRow(0), contains('Sound:on'));

    // Run a cycle
    await engine.tick();
    expect(engine.isStatusLineEnabled, isTrue);
    expect(getRow(0), contains('Score: 186 of 250'));
    expect(getRow(0), contains('Sound:on'));
  });
}
